- name: Restart prometheus
  listen: restart-prometheus
  become: true
  systemd:
    name: prometheus
    state: restarted
    daemon_reload: true

- name: Restart node_exporter
  listen: restart-node-exporter
  become: true
  systemd:
    daemon_reload: true
    name: node_exporter
    state: restarted