---
# TODOs
# - reload services on change
# - modularize
# - store secrets encrypted
# - cron for postgres backup (pg_dumpall | tar --use-compress-programm=pixz -cJf postgres-$(date foobar).tar.xz
- hosts: all
  vars:
    domain: klingt.vnet
    domain_version: unknown
    db_name: klingt-net
    # TODO encrypt this!
    db_password: ThisIsInsecure
    postgres_host: localhost
    postgres_port: 5432
    pgweb_path: /usr/bin/pgweb
    pgweb_port: 9999
    gitea_path: /usr/bin/gitea
    gitea_user: gitea
    gitea_group: gitea
    gitea_port: 10000
    gitea_db_name: gitea
    gitea_db_password: ThisIsInsecure
    gitea_admin_password: ThisIsInsecure
    jupyter_user: jupyter
    jupyter_group: jupyter
    jupyter_port: 10001
    caddy_user: caddy
    caddy_group: caddy
    caddy_path: /usr/bin/caddy
    caddy_email: admin@klingt.net
    caddy_ca_url: https://acme-staging.api.letsencrypt.org/directory
    caddy_prometheus_port: 9180
    caddy_restic_path: "/home/{{ caddy_user }}/restic"
    caddy_restic_user: alinz
    caddy_restic_password: ThisIsInsecure
    caddy_file_browser_root: "/var/caddy/files.{{ domain }}"
    # ThisIsInsecure
    jupyter_password: 'sha1:7ba04f8b7db3:b647b05c2e317857828f9f4fc929b08d485f9c76'
    prometheus_path: /usr/bin/prometheus
    prometheus_config_path: /etc/prometheus/config.yml
    prometheus_port: 9090
    node_exporter_path: /usr/bin/node_exporter
    node_exporter_port: 9091
    node_exporter_address: "127.0.0.1:{{ node_exporter_port }}"
    grafana_domain: "grafana.{{ domain }}"
    grafana_user: grafana
    grafana_password: ThisIsInsecure
    grafana_group: grafana
    grafana_address: 127.0.0.1
    grafana_port: 10002
    grafana_db_name: grafana
    grafana_db_password: ThisIsInsecure
    user_name: alinz
    user_password: ThisIsInsecure
    user_email: alinz@email.provider
    locale: en_US.UTF-8
  roles:
    - common
    - postgres
    - gitea
    - jupyter
    - caddy
    - prometheus
    - grafana
  tasks:
  - name: Set version number
    delegate_to: localhost
    shell: git describe --always --tags
    register: git_version
  - set_fact:
      domain_version: "{{ git_version.stdout }}"